version: '3'
services:
  backend:
    build: ./backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./app:/workspace/app
      - ./data:/workspace/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - qdrant
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: classy
      POSTGRES_PASSWORD: classy
      POSTGRES_DB: classydb
    ports:
      - "5432:5432"
